/* Vulkan-рендерер игры. */
#include "engine/graphics/types.inc"
#include "engine/graphics/geometry.inc"
#include "engine/graphics/vulkan_backend.inc"
#include "engine/graphics/autoscale.inc"
#include "engine/graphics/lifecycle.inc"
#include "engine/graphics/tri.inc"
#include "engine/graphics/tex_round.inc"
#include "engine/graphics/frame_lifecycle.inc"
#include "engine/graphics/fallback_screen.inc"
